# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget date::date date::date-tz)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target date::date
add_library(date::date INTERFACE IMPORTED)

set_target_properties(date::date PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ONLY_C_LOCALE=0"
  INTERFACE_INCLUDE_DIRECTORIES "/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/lib/date/include"
  INTERFACE_SOURCES "/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/lib/date/include/date/date.h;/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/lib/date/include/date/solar_hijri.h;/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/lib/date/include/date/islamic.h;/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/lib/date/include/date/iso_week.h;/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/lib/date/include/date/julian.h"
)

# Create imported target date::date-tz
add_library(date::date-tz STATIC IMPORTED)

set_target_properties(date::date-tz PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "USE_OS_TZDB=1"
  INTERFACE_INCLUDE_DIRECTORIES "/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/lib/date/include"
  INTERFACE_LINK_LIBRARIES "date::date;Threads::Threads"
  INTERFACE_SOURCES "/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/lib/date/include/date/tz.h"
)

# Import target "date::date-tz" for configuration "Debug"
set_property(TARGET date::date-tz APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(date::date-tz PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/c/Users/Mario/Documents/GitHub/metricq/metricq-cpp/build-ninja/lib/date/libdate-tz.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
