name: C++ Interface

on: [push]


jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        compiler: [g++-7, g++-8, g++-9, g++-10, clang++-8, clang++-9, clang++-10]
        include:
          - os: ubuntu-16.04
            compiler: clang++-6.0

    runs-on: {{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Protobuf
      run: |
        sudo apt update
        sudo apt install libprotoc-dev protobuf-compiler
    - name: Run CMake configure
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake .
    - name: Build
      run: make
    - name: Run CTest
      run: ctest .

  build-macos:

    runs-on: macos-latest

    strategy:
      matrix:
        xcode: [default]

    steps:
    - uses: actions/checkout@v2
    - name: Install Protobuf
      run: |
        brew install protobuf openssl@1.1
    - name: Select XCode
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      if: matrix.xcode != 'default'
    - name: Run CMake configure
      run: cmake . -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/
    - name: Build
      run: make
    - name: Run CTest
      run: ctest .
